[project]
name = "my-dl-project"
version = "0.1.0"
requires-python = ">=3.8"

dependencies = [
    "torch==2.1.0",
    "numpy==1.23.5",
    "scikit-learn==1.1.3",
    "pandas==1.5.3",
    "scipy==1.9.3",
    "rdkit-pypi==2022.9.5",
    "matplotlib==3.6.2",
    "networkx==2.8.8",
]
